// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef ATTRACKT_SWIFT_H
#define ATTRACKT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Attrackt",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;
enum AttracktEnvironment : NSInteger;
@protocol AttracktDelegate;

SWIFT_CLASS("_TtC8Attrackt8Attrackt")
@interface Attrackt : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Attrackt * _Nonnull shared;)
+ (Attrackt * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Attrackt * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)loadPlacementsWithPlacementId:(NSArray<NSString *> * _Nonnull)placementId;
+ (void)loadPlacementWithPlacementId:(NSString * _Nonnull)placementId;
+ (void)playAdWithPlacementId:(NSString * _Nonnull)placementId;
- (NSString * _Nonnull)unityStartWithApiKey:(NSString * _Nonnull)apiKey unityDelegate:(id _Nullable)unityDelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)startWithApiKey:(NSString * _Nonnull)apiKey environment:(enum AttracktEnvironment)environment delegate:(id <AttracktDelegate> _Nullable)delegate;
@end

typedef SWIFT_ENUM(NSInteger, AttracktAdFinishedState, open) {
/// <ul>
///   <li>
///     A state that indicates that the ad did not successfully display.
///   </li>
/// </ul>
  AttracktAdFinishedStateError = 1,
/// <ul>
///   <li>
///     A state that indicates that the user skipped the ad.
///   </li>
/// </ul>
  AttracktAdFinishedStateSkipped = 2,
/// <ul>
///   <li>
///     A state that indicates that the ad was played entirely.
///   </li>
/// </ul>
  AttracktAdFinishedStateCompleted = 3,
};

@class NSNumber;
enum AttracktSupportedAdvertisers : NSInteger;
@class NSError;

SWIFT_PROTOCOL("_TtP8Attrackt19AttracktAdsDelegate_")
@protocol AttracktAdsDelegate <NSObject>
- (void)didClickInterstitialWithAdType:(NSInteger)adType advertiser:(enum AttracktSupportedAdvertisers)advertiser placement:(NSString * _Nonnull)placement;
- (void)interstitialDidCloseWithAdType:(NSInteger)adType advertiser:(enum AttracktSupportedAdvertisers)advertiser placement:(NSString * _Nonnull)placement state:(enum AttracktAdFinishedState)state;
- (void)interstitialDidFailToLoadWithErrorWithError:(NSError * _Nonnull)error;
- (void)interstitialDidFailToShowWithErrorWithError:(NSError * _Nonnull)error;
- (void)interstitialDidLoadWithAdType:(NSInteger)adType advertiser:(enum AttracktSupportedAdvertisers)advertiser placement:(NSString * _Nonnull)placement;
- (void)interstitialDidOpenWithAdType:(NSInteger)adType advertiser:(enum AttracktSupportedAdvertisers)advertiser placement:(NSString * _Nonnull)placement;
- (void)interstitialDidShowWithAdType:(NSInteger)adType advertiser:(enum AttracktSupportedAdvertisers)advertiser placement:(NSString * _Nonnull)placement;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC8Attrackt23AttracktAdvertisementVc")
@interface AttracktAdvertisementVc : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8Attrackt14AttracktBanner")
@interface AttracktBanner : AttracktAdvertisementVc
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP8Attrackt22AttracktBannerDelegate_")
@protocol AttracktBannerDelegate
@optional
- (void)bannerDidAppeared;
- (void)bannerDissAppeared;
- (void)bannerLoadedWithSuccess;
- (void)bannerLoadFailed;
- (void)bannerTapped;
@end

@class AttracktError;

SWIFT_PROTOCOL("_TtP8Attrackt16AttracktDelegate_")
@protocol AttracktDelegate
- (void)onAttracktErrorWithError:(AttracktError * _Nonnull)error;
- (void)onAttracktSdkInitSuccess;
- (void)onAttracktReadyToPlayAd;
@end

typedef SWIFT_ENUM(NSInteger, AttracktEnvironment, open) {
  AttracktEnvironmentProduction = 0,
  AttracktEnvironmentTesting = 1,
};


SWIFT_CLASS("_TtC8Attrackt13AttracktError")
@interface AttracktError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, AttracktErrorAction, open) {
  AttracktErrorActionInit = 0,
  AttracktErrorActionLoadAdvertisers = 1,
  AttracktErrorActionLoadAdsetsForPlacement = 2,
};

typedef SWIFT_ENUM(NSInteger, AttracktErrorType, open) {
  AttracktErrorTypeConnectivity = 0,
  AttracktErrorTypeAPI = 1,
};


SWIFT_CLASS("_TtC8Attrackt11AttracktIAP")
@interface AttracktIAP : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SKProductsRequest;
@class SKProductsResponse;
@class SKRequest;

@interface AttracktIAP (SWIFT_EXTENSION(Attrackt)) <SKProductsRequestDelegate>
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end



@class SKPaymentQueue;
@class SKPaymentTransaction;

@interface AttracktIAP (SWIFT_EXTENSION(Attrackt)) <SKPaymentTransactionObserver>
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(SKPaymentQueue * _Nonnull)queue;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue restoreCompletedTransactionsFailedWithError:(NSError * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP8Attrackt19AttracktIAPDelegate_")
@protocol AttracktIAPDelegate
@optional
- (void)OnPurchaseCompleteWithSku:(NSString * _Nonnull)sku;
- (void)OnAllReadyPurchaseCompleteWithSku:(NSString * _Nonnull)sku;
- (void)OnPurchaseFailedWithSku:(NSString * _Nonnull)sku error:(NSString * _Nonnull)error;
@end


SWIFT_PROTOCOL("_TtP8Attrackt28AttracktInterstitialDelegate_")
@protocol AttracktInterstitialDelegate
- (void)interstitialDidClosedWithAdState:(enum AttracktAdFinishedState)adState;
- (void)interstitialLoadSuccess;
- (void)interstitialDidOpen;
- (void)interstitialDidShow;
- (void)interstitialLoadFailedWithFailError:(NSString * _Nonnull)failError;
- (void)interstitialShowFailedWithFailError:(NSString * _Nonnull)failError;
- (void)interstitialTapped;
@end

@class SRCountdownTimer;

SWIFT_PROTOCOL("_TtP8Attrackt24SRCountdownTimerDelegate_")
@protocol SRCountdownTimerDelegate
@optional
- (void)timerDidUpdateCounterValueWithSender:(SRCountdownTimer * _Nonnull)sender newValue:(NSInteger)newValue;
- (void)timerDidStartWithSender:(SRCountdownTimer * _Nonnull)sender;
- (void)timerDidPauseWithSender:(SRCountdownTimer * _Nonnull)sender;
- (void)timerDidResumeWithSender:(SRCountdownTimer * _Nonnull)sender;
- (void)timerDidEndWithSender:(SRCountdownTimer * _Nonnull)sender elapsedTime:(NSTimeInterval)elapsedTime;
@end

@class WKWebView;
@class WKNavigation;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class SKStoreProductViewController;

SWIFT_CLASS("_TtC8Attrackt22AttracktInterstitialVC")
@interface AttracktInterstitialVC : AttracktAdvertisementVc <SRCountdownTimerDelegate, SKStoreProductViewControllerDelegate, WKNavigationDelegate, WKUIDelegate>
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)timerDidEndWithSender:(SRCountdownTimer * _Nonnull)sender elapsedTime:(NSTimeInterval)elapsedTime;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)productViewControllerDidFinish:(SKStoreProductViewController * _Nonnull)viewController;
@end

typedef SWIFT_ENUM(NSInteger, AttracktSupportedAdvertisers, open) {
  AttracktSupportedAdvertisersVungle = 1,
  AttracktSupportedAdvertisersIronSource = 2,
  AttracktSupportedAdvertisersAdmob = 3,
  AttracktSupportedAdvertisersAdColony = 4,
  AttracktSupportedAdvertisersChartboost = 5,
  AttracktSupportedAdvertisersUnity = 6,
  AttracktSupportedAdvertisersAppLovin = 8,
  AttracktSupportedAdvertisersFacebook = 9,
  AttracktSupportedAdvertisersMoPub = 10,
  AttracktSupportedAdvertisersAttrackt = 11,
};


SWIFT_CLASS("_TtC8Attrackt11BaseAdapter")
@interface BaseAdapter : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




/// ▶️ Player, simple way to play and stream media
SWIFT_CLASS("_TtC8Attrackt6Player")
@interface Player : UIViewController
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
@end








SWIFT_CLASS("_TtC8Attrackt10PlayerView")
@interface PlayerView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class UIColor;
@class UIFont;

SWIFT_CLASS("_TtC8Attrackt16SRCountdownTimer")
@interface SRCountdownTimer : UIView
@property (nonatomic) IBInspectable CGFloat lineWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull lineColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull trailLineColor;
@property (nonatomic) IBInspectable BOOL isLabelHidden;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable labelFont;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable labelTextColor;
@property (nonatomic, copy) IBInspectable NSString * _Nullable timerFinishingText;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
@end



SWIFT_CLASS("_TtC8Attrackt17SwiftConfettiView")
@interface SwiftConfettiView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

















SWIFT_CLASS("_TtC8Attrackt26VideoImageEndCardLandScape")
@interface VideoImageEndCardLandScape : AttracktAdvertisementVc <SRCountdownTimerDelegate>
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)timerDidEndWithSender:(SRCountdownTimer * _Nonnull)sender elapsedTime:(NSTimeInterval)elapsedTime;
- (void)viewDidDisappear:(BOOL)animated;
@end


SWIFT_CLASS("_TtC8Attrackt25VideoImageEndCardPortrait")
@interface VideoImageEndCardPortrait : AttracktAdvertisementVc <SRCountdownTimerDelegate>
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)timerDidEndWithSender:(SRCountdownTimer * _Nonnull)sender elapsedTime:(NSTimeInterval)elapsedTime;
- (void)viewDidDisappear:(BOOL)animated;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
